### ISSUE TITLE
image show problem

### ISSUE THREAD

**Issue by TYTVF** [UndefinedAli/AzureDataCapture#1]
Thank you for sharing the code.  I used to display the depth image and the infrared image but it had a ghost in a window and I don't know how to solve this problem

**Comment by UndefinedAli** [comment]
Sorry to reply to you so late.
Are you talking about ghost as a shadow around the foreground object?

**Comment by UndefinedAli** [comment]
> Thank you for sharing the code. I used to display the depth image and the infrared image but it had a ghost in a window and I don't know how to solve this problem

Sorry to reply to you so late.
Are you talking about ghost as a shadow around the foreground object?

**Comment by TYTVF** [comment]
such as
![IYK0HQ8C`VAY8YDEW2F2X{U](https://user-images.githubusercontent.com/52398054/66365810-dea72780-e9c0-11e9-9196-99a8512342a4.png)
i use the CV_8U not CV_16.
if i use CV_16 then i use imshow will report an error.

**Comment by UndefinedAli** [comment]
> such as
> ![IYK0HQ8C`VAY8YDEW2F2X{U](https://user-images.githubusercontent.com/52398054/66365810-dea72780-e9c0-11e9-9196-99a8512342a4.png)
> i use the CV_8U not CV_16.
> if i use CV_16 then i use imshow will report an error.

Depth and infrared in Azure's SDK are stored in 16bit unsigned char (CV_16U).
Please try to use cvConvertScale() convert 16-bit to 8-bit before imshow()
